suppressPackageStartupMessages({
  library(vvbitwarden)
  library(purrr)
  library(httr2)
  library(jsonlite)
  library(dplyr)
  library(tidyr)
  library(readr)
  library(stringr)
  library(lubridate)
  library(logger)
  library(openssl)
  library(xts)
  library(quantmod)
  library(AzureStor)
  library(AzureAuth)
  # library(TTR)
  # library(fs)
  # library(config)
  # library(ggplot2)
})